### ISSUE TITLE
Unable to apply changes on device: emulator-5554. Error is: cp: no such file or directory: D:\DEVELOPMENT\GIT\ngatl\apps\mobile\node_modules\tns-android\framework\libs

### ISSUE THREAD

**Issue by TimPickin** [ngatl/ngatl#22]
I used the wwwalkerrun/nativescript-ngx-magic in a project, and am now trying to switch to using the nx workspace. I am taking this project as an example, I have cloned it and run npm install but I am getting the following error with nativescript.

I can use the npm run start command to run the website. It is hosted on localhost:4200

But when I use the npm run start.android I get the error:
Unable to apply changes on device: emulator-5554. Error is: cp: no such file or directory: D:\DEVELOPMENT\GIT\ngatl\apps\mobile\node_modules\tns-android\framework\libs.

What am I doing wrong?

**Comment by TimPickin** [comment]
I fixed this by updating the local nativescript-cli version on my machine.

**Comment by zackarychapple** [comment]
Cool beans! /cc @NathanWalker
